add missing dep
fix a dependency issue

Traceback (most recent call last):                                                                                                                                                                                
  File "mr.sip.py", line 37, in <module>                                                                                                                                                                          
    import random,string,ipaddress,netifaces,os,socket,logging                                                                                                                                                    
ImportError: No module named netifaces