wascan: fix dependency
it requires BS3 not 4

BS 4

```
$  wascan --help             
Traceback (most recent call last):
  File "wascan.py", line 37, in <module>
    from lib.handler.crawler import *
  File "/usr/share/wascan/lib/handler/crawler.py", line 10, in <module>
    from lib.request.crawler import SCrawler
  File "/usr/share/wascan/lib/request/crawler.py", line 15, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
```

BS 3

```
$ wascan --help             
__________________________________________________
 ________ _______ _______                   
|  |  |  |   _   |     __|.----.---.-.-----.
|  |  |  |       |__     ||  __|  _  |     |
|________|___|___|_______||____|___._|__|__|
                                      v0.2.1
      WAScan - Web Application Scanner      
           C0d3n4m3: ATLAS                  
          Momo Outaadi (m4ll0k)             
__________________________________________________

__________________________________________________
 ________ _______ _______                   
|  |  |  |   _   |     __|.----.---.-.-----.
|  |  |  |       |__     ||  __|  _  |     |
|________|___|___|_______||____|___._|__|__|
                                      v0.2.1
      WAScan - Web Application Scanner      
           C0d3n4m3: ATLAS                  
          Momo Outaadi (m4ll0k)             
__________________________________________________

Usage: wascan.py [options]

        -u --url        Target URL (e.g: http://www.site.com)
        -s --scan       Scan options (default=5):

                0 :     Fingerprint (server,waf,cms,...)
                1 :     Attacks (sql,ldap injection,...)
                2 :     Audit (phpinfo,openredirect,...)
                3 :     Bruteforce (dir,file,backup,...)
                4 :     Disclosure (emails,password,...)
                5 :     Full scan (audit,attacks,brute,...)

        -b --brute      Bruteforce hidden parameters (GET only)
        -H --headers    Extra headers (e.g: "Host:site.com")
        -d --data       Data to be sent via POST method
        -m --method     HTTP method, GET or POST
        -h --host       HTTP Host header value
        -R --referer    HTTP Referer header value
        -a --auth       HTTP Basic Authentication (user:pass)
        -A --agent      HTTP User-agent header value
        -r --ragent     Use random User-agent header value
        -c --cookie     HTTP Cookie header value
        -p --proxy      Use a proxy, (host:port)
        -P --proxy-auth Proxy Authentication, (user:pass)
        -t --timeout    Seconds to wait before timeout connection
        -n --redirect   Set redirect target URL False (default=True)
        -v --verbose    Verbosity, print more informations
        -V --version    Show tool version
        -hh --help      Show this help and exit

Examples:

        wascan.py --url http://www.site.com/
        wascan.py --url http://www.site.com/test.php --brute
        wascan.py --url http://www.site.com/ --scan [0,2,4]
        wascan.py --url http://www.site.com/ --auth "admin:1233"
        wascan.py --url http://www.site.com/index.php?id=1 --scan [1,4]
        wascan.py --url http://www.site.com/index.php --data "id=1" --method POST --scan [1,4]
        wascan.py --url http://www.site.com/index.php?id=1 --scan [1,4] --headers "Host: site.com,..."
        wascan.py --url http://www.site.com/ --scan [0,2,4] --proxy 10.10.10.10:80 --proxy-auth "root:1234"

See this page https://github.com/m4ll0k/WAScan for more examples
```